"""Window sizing constants for auxiliary frames."""

OPPONENT_TRACKER_FRAME_SIZE = (740, 600)
OPPONENT_TRACKER_MIN_SIZE = (600, 400)
OPPONENT_TRACKER_DEFAULT_X_GAP = 8
OPPONENT_TRACKER_LABEL_WRAP_WIDTH = 320
OPPONENT_TRACKER_SECTION_PADDING = 6
OPPONENT_TRACKER_LEFT_SASH_POS = 280
OPPONENT_TRACKER_RADAR_PANEL_HEIGHT = 160  # px allocated to radar panel in left splitter

# Sideboard Guide — Import Options dialog
GUIDE_IMPORT_OPTIONS_DIALOG_WIDTH = 400
GUIDE_IMPORT_OPTIONS_DIALOG_HEIGHT = 150
